-- User-generated models table.
-- Each row is a private AI model photo generated by a specific user from a preset template.
-- Row-level security ensures users can only access their own rows.

CREATE TABLE IF NOT EXISTS user_models (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name            TEXT        NOT NULL,
  storage_path    TEXT        NOT NULL,
  public_url      TEXT,
  source_template_id UUID     REFERENCES marketplace_templates(id) ON DELETE SET NULL,
  gender          TEXT        NOT NULL DEFAULT 'man',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE user_models ENABLE ROW LEVEL SECURITY;

CREATE POLICY "user_models_select"
  ON user_models FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "user_models_insert"
  ON user_models FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "user_models_delete"
  ON user_models FOR DELETE
  USING (auth.uid() = user_id);

-- Index for fast per-user lookups
CREATE INDEX IF NOT EXISTS user_models_user_id_idx ON user_models (user_id, created_at DESC);
